server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lelodois/twitter-client-conf

eureka:
  instance:
    hostname: 172.18.0.21
    port: 8091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
